### ISSUE TITLE
Looking for paid to develop this site and deploy to my server

### ISSUE THREAD

**Issue by qooboy** [Reloadly/sample-airtime-topup-platform#15]
I need to make a top-up website, if you can re-develop this website to meet our needs, I am willing to pay the fee
Requirement 1: Pay with USDT/WeChat/Alipay/Paypal/Credit card

**Comment by qooboy** [comment]
> I need to make a top-up website, if you can re-develop this website to meet our needs, I am willing to pay the fee Requirement 1: Pay with USDT/WeChat/Alipay/Paypal/Credit card

E-mail:szlaoding@gmail.com

**Comment by junaidmaqbutt** [comment]
Hi, Hope all is well. 

If there is any generic change that you think could benefit the whole community you can contact Reloadly support regarding it or open a ticket for that. If there is enough demand we might be able to push work on that to update the whole repository. 

The project is openly available for you to customize or install as per your own requirement. 

If you need more help or customization feel free to contact us at junaidmaqbutt@otifsolutions.pk
